-- Script was generated by Devart dbForge Studio for MySQL, Version 6.1.166.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 7/14/2014 10:22:25 AM
-- Server version: 5.6.19
-- Client version: 4.1

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set default database
--
USE ProductDB;

--
-- Definition for table cds
--
DROP TABLE IF EXISTS CDS;
CREATE TABLE CDS (
  FullIndexName VARCHAR(255) NOT NULL DEFAULT ' ',
  DojimaProductType VARCHAR(255) NOT NULL DEFAULT ' ',
  Market VARCHAR(255) NOT NULL DEFAULT ' ',
  IndexFamily VARCHAR(255) DEFAULT NULL,
  IndexSeries INT(11) DEFAULT NULL,
  IndexVersion INT(11) DEFAULT NULL,
  Sector VARCHAR(255) DEFAULT NULL,
  CouponRate DOUBLE DEFAULT NULL,
  Tenor VARCHAR(255) DEFAULT NULL,
  MarkitTicker VARCHAR(255) DEFAULT NULL,
  RequiredForClearing VARCHAR(1) DEFAULT NULL,
  ClearingDate DATE DEFAULT NULL,
  MaturityDate DATE DEFAULT NULL,
  EffectiveDate DATE DEFAULT NULL,
  AnnexDate DATE DEFAULT NULL,
  MarkitRed VARCHAR(20) NOT NULL DEFAULT ' ',
  ClearingEligibleISIN VARCHAR(15) DEFAULT NULL,
  PreferredISIN VARCHAR(15) DEFAULT NULL,
  Currency VARCHAR(3) DEFAULT NULL,
  ClearingCode VARCHAR(255) DEFAULT NULL,
  Snrty VARCHAR(255) DEFAULT NULL,
  RestrictType VARCHAR(255) DEFAULT NULL,
  IndexWeight INT(11) DEFAULT NULL,
  CurrentlyActive VARCHAR(2) DEFAULT NULL,
  Tier VARCHAR(255) DEFAULT NULL,
  Clause VARCHAR(255) DEFAULT NULL,
  INDEX IDX_cds_ClearingEligibleISIN (ClearingEligibleISIN),
  INDEX UK_cds_MarkitRed (MarkitRed)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 174
CHARACTER SET utf8
COLLATE utf8_general_ci;

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;